import {useSelector} from 'react-redux';
export const useTranslation = () => {
  const textStringEng = {
    emailAlreadyInUse: 'Email is already in use.',
    phoneAlreadyInUse: 'Phone number is already in use.',
    invalidEmailError: 'Email address is invalid.',
    invalidVerficationCodeError: 'Invalid verification code',
    carPlateNumberErrorAlert: 'Duplicate plate number found, skipping save',
    productHasBeenDeleted: 'Product details are being loaded.',
    aboutUsQuestion1: 'About Us',
    aboutUsQuestion2: 'Our Service',
    aboutUsQuestion3: 'Our vision',
    aboutUsQuestion4: 'Our goals',
    aboutUsQuestion5: 'Our values',
    oilFilterTitleTxt: 'Oil & Filters',
    filtersfiltersNameTxtHead: 'Filters',
    noFiltersFoundTxt: 'No Filters available for your Car',
    discountTxt: 'Discount',
    tiresTitleTxt: 'Tires',
    supportSrviceHomeSubTxt: '(guarantee & subscription)',
    aboutUsAnswer1:
      'The zurex app is a one stop application for Ismail Al Jamaan Al Hamrani Trading Company, a leader in the field of car batteries, car tires and the import of car parts and accessories, at the level of the kingdom of Saudi Arabia, and our activity and services extend to a wide range throughout the kingdom through our branches .It is the exclusive agent of the AC ZUREX and CAMEL brand in the kingdom.',
    aboutUsAnswer2:
      'We work at Ismail Al Jamaan Al Hamrani Trading Company to provide the best types of car batteries, car tires, car parts and accessories to all our customers with the required quality, we are one of the leading distributors of various brands and of batteries and tires from Korea, Taiwan and Indonesia ,Thailand, China, homemade.',
    aboutUsAnswer3:
      'The Corporation intends to be the leader in its field in the wholesale and retail trade of auto products, spare parts and accessories, and the sale of high-quality car and truck batteries and tires in the Kingdom, and to achieve its vision through sustainable growth through innovation in development and prosperity with the best international products and the provision of an advanced workforce of engineers and consultants.',
    aboutUsAnswer4:
      'Providing the best quality products and effective after-sales services at the national level, and we are working to develop them in parallel with the local and international markets with high-quality environmentally friendly products and a guarantee. Customer satisfaction is the goal of our company, and we want to constantly reach and explore global markets.',
    aboutUsAnswer5:
      'The real wealth of the company lies in its solid relationships. We consider it the cornerstone in the construction and management of our company, which is one of the constants that we do not deviate from, and strives to understand their requirements and needs.',
    btnLess: 'Show Less',
    btnMore: 'More',
    myCars: 'My Cars',
    addACar: 'Add a car',
    ComingSoon: 'Coming Soon !',
    addCar: 'Add car',
    selectCarType: 'Select car name',
    selectCarCatg: 'Car manufacturer',
    selectCarModal: 'Car model',
    writePlateNumber: 'Write down plate number',
    writePlateTxt: 'Write down plate Text',
    myOrder: 'My Order',
    now100: 'Now 100',
    later125: 'Later 125',
    save25: 'Save 125',
    priceTxt: 'Price',
    wagesTxt: 'Service Charges & Installation',
    promoCodeTxt: 'Promotion',
    subscriptionTxt: 'Subscription',
    taxTxt: 'Tax',
    tabbyNoEnoughLimit:
      'You do not have enough limit to complete this payment.',
    tabbyOrderHighError:
      'This purchase is above your current spending limit with Tabby, try a smaller cart or use another payment method',
    tabbyTooLowError:
      'The purchase amount is below the minimum amount required to use Tabby, try adding more items or use another payment method',
    tabbyGeneralError:
      'Sorry, Tabby is unable to approve this purchase. Please use an alternative payment method for your order.',
    cashbackTxt: 'Cashback',
    completeOrder: 'Complete Order',
    fuelTypeTxt: 'Fuel Type',
    petrol: 'Petrol',
    diesel: 'Diesel',
    orderSuccess: 'Order Successfull',
    completeOrder2: 'Complete Payment',
    locationTxt: 'Location',
    timeTxt: 'Time',
    confirmationTxt: 'Confirmation',
    balanceTxt: 'Balance',
    balanceSubTxt: '(cashback)',
    supportTxt: 'Support services',
    supportSubTxt: '(battery charge and warranty)',
    currencyTxt: 'SAR',
    requestTxt: 'requests',
    curntLocationTxt: 'Your current location',
    openGpsSetting: 'Open GPS Settings',
    gpsDisabled: 'GPS is disabled. Please enable it in settings.',
    locationPermissionDenied:
      'Location permission denied. Please enable it in settings.',
    selectLocationTxt: 'Locate on a map',
    batteryTxt: 'Batteries',
    singleBatteryTxt: 'Battery',
    descriptionTxt: 'Description',
    itemNoTxt: 'Item No',
    ampereTxt: 'Ampere',
    lengthTxt: 'Length',
    widthTxt: 'Width',
    heightTxt: 'Height',
    chooseDateTxt: 'Date',
    chooseTimeTxt: 'Time',
    chooseBateryTxt: 'Select the type of battery',
    chooseTireTxt: 'Select the type of tires',
    totalHeightTxt: 'Total height',
    noResultsFound: 'No search results found',
    coolEngyTxt: 'Cool energy cycling',
    acZurexBatteryTxt: 'Ac zurex battery',
    camelBatteryTxt: 'Camel battery',
    ePayTxt: 'Electronic Payment',
    installTxt: 'Installment Companies',
    cashPayTxt: 'Cash Payment',
    riyazTxt: 'Riyadh',
    nextTxt: 'Next',
    carsTxt: 'Cars',
    contactUsTxt: 'Conatact Us',
    seventhCategoryTxt: 'Seventh Category',
    carCategoryTxt: 'Category',
    carPlateTxt: 'Plate',
    whatsappTxt: 'Whatsapp',
    instagramTxt: 'Instagram',
    tiktokTxt: 'Tiktok',
    snapchatTxt: 'Snapchat',
    twitterTxt: 'Twiter',
    emailTxt: 'Email',
    mobileTxt: 'Mobile',
    plateplaceTxt:
      'Enter the letters, whether Arabic or English, in the left-to-right',
    selectFuelType: 'Select Fuel Type',
    contactUsDescTxt:
      'Contact us on one of these method and we make every effort to respond to your inquiries as soon as possible',
    confirmCarDataTxt: 'Confirm the car data is correct',
    n100BatteryDescTxt:
      "An electronic car battery made in Malaysia that doesn't require maintenance",
    camelBatteryDescTxt: 'Chinese electric car battery',
    addWarentytxt: 'Add examination, subscription and warranty service',
    faqQuestion1: 'What types of batteries do we supply',
    faqAnswer1:
      'We offer all types of ac zurex batteries, made in Malaysia, that last for a full year, as we are the exclusive agent for this brand in the Kingdom of Saudi Arabia.',
    faqQuestion2: 'What about the quality of the batteries',
    faqAnswer2:
      'All products we sell meet the requirements set by the relevant country of Saudi Arabia',
    faqQuestion3: 'Why there is a big difference in prices',
    faqAnswer3:
      'The difference is due to the quality and quality of the batteries.',
    faqQuestion4: 'How can I buy a battery from ac zurex store',
    faqAnswer4:
      'Enter your data on the store, then choose the preferred battery to the cart list, then fill in the payment information, and we will contact you and send the battery to your place with our installation team.',
    faqQuestion5: 'Is the battery under warranty',
    faqAnswer5:
      'Each battery comes with a standard warranty.\nThe warranty is void if the battery is used in the wrong way',
    faqQuestion6: 'Can I buy a battery from you and ship it to my country',
    faqAnswer6:
      'Yes, we can ship a large amount to you via your shipping companies. Please contact us via email or technical support',
    faqQuestion7: 'Is there a refund and replacement',
    faqAnswer7:
      'There is no return or exchange, but only according to the warranty card that came with the battery',
    faqQuestion8: 'Can my old car battery be replacedwith an ac zurex battery',
    faqAnswer8:
      'Yes, you can replace your battery with a battery from ac zurex with a discount of 30 SAR on a code',
    faqTitleTxt: 'FAQ',
    orderIDTxt: 'Order Id',
    serviceDateTxt: 'Service date',
    validWarntyBtnTxt: 'Warranty validity is valid',
    inValidWarntyBtnTxt: 'Warenty is not valid',
    serviceDateImpltTxt: 'Date of service implementation',
    waitTitleTxt: 'Please wait a while\nfor it to work',
    idVerificationTitle: 'Verification of your identity',
    verfIdSubTxt:
      'Please enter your ID number to continue the verification process please make sure to enter the ID number associated with the mobile number',
    verfIdSubTxt1:
      'This information will be used to authenticate your identity as stipulated by the teachings of the Saudi central bank',
    lernMoreTxt: 'Learn more',
    back: 'Back',
    resdNumTxt: 'ID / residence number',
    followUpTxt: 'Follow Up',
    vIdModelMainTxt: 'Be sure to download and activate the Nafath application',
    vIdModelSubTxt:
      'To verify your identity and complete the payment process using Tamara, please make sure that Nafath application is available',
    vIdModelbtn1Txt: 'Follow-up to the verfication process',
    vIdModelbtn2Txt: 'Download Nafath app',
    enterVerfCodeTxt: 'Enter Verfication Code',
    enterVerfSubTxt:
      'We sent a text message with a verification code of 6 Numbers for your mobile number',
    enterVerfChangNum: 'Change Mobile Number',
    verfCode: 'Verification Code',
    reSendTxt: 'Re-send',
    loginInputFieldTxt1: 'Mobile No.',
    loginBtnTxt: 'Login',
    dontAccount: "Don't have an acoount?",
    createTxt: 'Create account',
    myCarBilltitle1: 'Machine Wash Oil',
    myCarBilltitle2: 'Brake Oil',
    myCarBilltitle3: 'Drexon Oil',
    myCarBilltitle4: 'Gear Oil',
    myCarBilltitle5: 'Radiator Water',
    chooseMethodTxt:
      'Please choose one of the methods below to\nenter your car data',
    successFullTxt: 'Sucessfull!',
    carDataUpdatedDone: 'Cars data updated successfully.',
    plateNumTxt: 'Plate Number',
    manualEnteryTxt: 'Manual Entry',
    privateTxt: 'Private',
    transferTxt: 'Transfer',
    addToCartTxt: 'Add to cart',
    anOtherReqTxt: 'Another service request',
    batteryListTxt: 'List of Batteries',
    oilListTxt: 'List of Oils',
    oilTxt: 'Oils',
    folowUpPayTxt: 'Follow up payment',
    currentBtnTxt: 'Current',
    perviosBtnTxt: 'Completed',
    comingBtnTxt: 'In Process',
    orderStatusComplete: 'Completed',
    orderStatusPanding: 'Pending',
    orderStatusApproved: 'Approved',
    orderStatusCanceled: 'Cancelled',
    invalidPhoneNumberError: 'Phone number must be 9 digits',
    numberOfOilRefills: 'Number of oil refills',
    typeOfOilTxt: 'Type of oil',
    selctFilterType: 'Please select filter type.',
    selectFuelTypeError: 'Please select a fuel type',
    oilFilterTxt: 'Oil Filter',
    airFilterTxt: 'Air Filter',
    airConditionerFilterTxt: 'Air Conditioner Filter',
    oilNameSelectTitle1: 'Ac zurex oil',
    oilNameSelectTitle2: 'Shell HELIX oil',
    oilNameSelectTitle3: 'Castrol oil',
    oilNameSelectTitle4: 'Mobile oil',
    oilOfferIncludedTxt: 'Cashback 10 % + Free Laundry',
    oilOfferNotIncludedTxt: 'Offer not included',
    loremTxt: 'Thank you for making order with Zurex',
    homeBtnTxt: 'Home',
    trackingOrderTxt: 'Tracking order',
    weRcevedOrderTxt: 'We received your Order',
    orderOnWayTxt: 'The order is on your way',
    orderCompletedTxt: 'Your order is completed',
    quantityTxt: 'Quantity',
    orderTimeTxt: 'Order time',
    recepiantAddressTxt: 'Recipient address',
    rateUsTxt: 'Rate Us',
    cancelTxt: 'Cancel',
    rateUsStoreTxt: 'Please rate us on store',
    goNowBtnTxt: 'Go Now',
    noBtnTxt: 'No',
    rateServiceProviderTxt: 'Please rate the service provider',
    serviceProvidedTxt: 'How was the service provided by us?',
    completeThePayTxt: 'Complete the payment',
    payCompletSuccess: 'Payment completed successfully',
    orderStatusTxt: 'Order status',
    payMethodTxt: 'Payment Methods',
    myProfileTxt: 'My Profile',
    userNameTxt: 'User Name',
    saveBtnTxt: 'Save',
    yearsOnlyTxt: 'years only',
    madeInFrance: 'Made in France',
    madeInJapan: 'Made in Japan',
    michlanTireTxt: 'Michelin tire',
    bridgeStoneTireTxt: 'Bridgestone tire',
    firstartcle: [
      {
        id: 0,
        question: 'Battery overcharging',
        answer:
          'Overcharging the battery causes it to suddenly stop working and damage it, so you have to be careful and check the condition of the electricity regulator if it is working well or if it is broken or there is a mistake in setting it, because all of the aforementioned leads to an increase in the charge in the battery and thus the decomposition and corrosion of the panels inside, which leads to It loses its power and exposes it to damage',
      },
      {
        id: 1,
        question: 'Not fully charging the battery',
        answer:
          'Malfunctions in the car’s electric system or its failure to adjust it well, in addition to loosening the fan belt in the car, cause the battery to not be fully charged, and the matter does not end here because this leads to the formation of a layer of salts on the battery plates that weakens its performance and exposes it to damage, especially if the defect is not addressed quickly.',
      },
      {
        id: 2,
        question:
          'Corrosion and contamination of the battery electrodes in the car',
        answer:
          'You need to pay close attention to the condition of the cables and connect them tightly with the battery terminals and make sure that they are clean and free of malfunctions because any malfunction in this leads to an increase in resistance at the terminals and thus the battery charging efficiency decreases, and then the voltage difference required to operate decreases Car engine',
      },
      {
        id: 3,
        question: 'The battery is not securely installed inside the car',
        answer:
          'This exposes it to vibration and thus the active substance falls and leaks from the battery plates, in addition to causing the secret of welding between the battery cells, which leads to damage to the battery and its cessation of work',
      },
      {
        id: 4,
        question:
          'Over-tightening the connection and installation of the battery',
        answer:
          'It can lead to damage to the battery box and the occurrence of a break or crack in it, and therefore leakage of material from the battery, which leads to damage to it and damage to other parts',
      },
      {
        id: 5,
        question: 'Car engine failure',
        answer:
          'A clear signal for diagnosing battery damage and a strong indicator of its weakness, and when the engine suffers any malfunction, frequent attempts to start the engine lead to depletion of the battery, which leads to its damage',
      },
      {
        id: 6,
        question: 'Frequent sudden stopping of the car while driving',
        answer:
          "The reason for this may be damage to the battery, poor quality of the generator or the fuel pump, and for this reason, if the car suddenly stops more than three times a week, most likely it's time to buy a new battery",
      },
      {
        id: 7,
        question: 'When to change the car battery',
        answer:
          'Each battery has a certain life span and you need to pay attention to the right time to change the battery, as you do not have to wait until it is completely damaged, but you can notice the indicators that tell you the ideal time for this so as to avoid sudden battery malfunctions',
      },
      {
        id: 8,
        question: 'Intermittent problems with the car',
        answer:
          'If you notice that your car is working well today and the next day you have a problem and so on, this is a sign that the battery has something wrong, such as being broken, its terminals are corroded or suffering from calcification, for this you should check its condition',
      },
    ],
    secondarticle: [
      {id: 0, answer: 'Start your search well'},
      {id: 1, answer: 'Choose the right time'},
      {id: 2, answer: 'Focus on price, not payments'},
      {id: 3, answer: 'Think about the color of the car'},
      {id: 4, answer: 'Make sure the car is checked by an expert'},
      {id: 5, answer: 'Think about the right car size'},
      {id: 6, answer: 'Choose a car that can be handled without complexity'},
      {id: 7, answer: 'Stay away from sports cars for their powerful engines'},
      {id: 8, answer: 'Think about maintenance'},
      {id: 9, answer: 'It is possible to think about a used car'},
    ],
    fortharticle: [
      {
        id: 0,
        answer:
          'The difficulty of starting the car engine, as you will notice that starting the car requires time and many attempts',
      },
      {
        id: 1,
        answer:
          'Lighting the battery marker in the dashboard is an indicator that you should not ignore , most often it indicates a problem with the charging system or damage to the battery',
      },
      {
        id: 2,
        answer:
          'The appearance of a bulge in the battery and deformation of its shape, and this happens as a result of overcharging the battery',
      },
      {
        id: 3,
        answer:
          'Liquid leakage from the battery, as liquid batteries tend to leak acid as a result of overcharging or damage, in any case, when this happens, you need to replace it immediately',
      },
    ],
    thirdarticle: [
      {id: 0, answer: 'Avoid short trips and driving close distances'},
      {
        id: 1,
        answer:
          'Be sure to turn off the interior and exterior lights when leaving the car',
      },
      {id: 2, answer: 'Keep the battery and wires constantly clean'},
      {
        id: 3,
        answer:
          'Avoid using electronic devices such as a radio when when the car engine is turned off',
      },
      {
        id: 4,
        answer: 'Park your car in the shade or in the garage to protect it',
      },
      {id: 5, answer: 'Make sure the thermal insulator is firmly in place'},
      {
        id: 6,
        answer:
          'Pay attention to indicators that tell you that your car battery has some problem or needs maintenance',
      },
    ],
    resons9TxtHead: '9 reasons why your car battery suddenly stopped working',
    secret10TxtHead:
      '10 secrets every woman should know before buying a new car',
    tip7HotHeadTxt: '7 tips to save your car battery in hot weather',
    replaceTimeTopHeadTxt:
      'How do you know when your car battery is time to replace?',
    tipsAndArticleTxt: 'Tips & articles',
    termsdataTxt: [
      {
        answer:
          'The store reserves the right to change parts of the terms and conditions of use, modify them, add some of them, or remove them at any time, and the changes become effective when they are published on the store without prior notice, so we hope that you review the terms and conditions periodically to keep abreast of all updates',
        id: 0,
      },
      {
        answer:
          'Your personal data and privacy are kept strictly confidential and are of interest to us',
        id: 1,
      },
      {
        answer:
          'Keep updating your data and information continuously during the purchase process, including your email address, credit card number and dates, so that we can complete your purchases on the store and communicate .With you when you need it',
        id: 2,
      },
      {
        answer:
          'The store has the possibility to withdraw the membership or suspend the account of customers who violate any of the terms of use',
        id: 3,
      },
      {
        answer:
          'A person cannot register as a member of the store more than once',
        id: 4,
      },
      {
        answer:
          'To complete the registration process, you must provide all your contact information',
        id: 5,
      },
      {
        answer: 'The sale only takes place if you accept the terms',
        id: 6,
      },
      {
        answer:
          'Take responsibility for all operations that take place under your account and your password',
        id: 7,
      },
      {
        answer:
          'We strive to provide all information regarding product pricing and to provide an accurate description of each of the products displayed in the store',
        id: 8,
      },
      {
        answer:
          'You may be fully responsible before the competent and judicial authorities if it is proven that you are using a misleading or false e-mail or impersonating another person for the purpose of misleading us so that we do not know the source',
        id: 9,
      },
      {
        answer:
          'Any of your comments or publishing infringing contents, viruses or malware that may harm the store',
        id: 10,
      },
      {
        answer:
          'We have the right, in the event of a violation of any of the previous clauses, to stop your use of the store.',
        id: 11,
      },
    ],
    termConditionTxt: 'Terms & Conditions',
    settingHedTxt: 'Setting',
    notificationTxt: 'Notifications',
    languageTxt: 'Language',
    languagNameTxt: 'English',
    deleteAccountTxt: 'Delete account',
    delAccountTitleTxt: 'Are you sure about deleting the account',
    yesSureTxt: 'Yes, i am sure',
    yesTxtLog: 'Yes',
    noTxtLog: 'No',
    attentionTxtLog: 'Attention',
    oilAttentionTxt:
      "We currently offer delivery only in Riyadh. To proceed, please tap 'Yes.'",
    rimTxt: 'Rim',
    singleTireTxt: 'tire',
    tiresDescTxt: 'Roadshine manufacturer',
    verifcationConfirmedTitle: 'Verification has been confirmed',
    verifcationConfirmedSubTitle:
      'The verification process has been successfully completed',
    UnVerifcationConfirmedTitle: 'The verification request was rejected',
    UnVerifcationConfirmedSubTitle:
      'The verification process was not completed successfully, please retry the verification process later',
    gettinHelpTxt: 'Getting Help',
    tamareaLoginTxt: 'Log in or create a new account',
    tamarMobileVerfSub:
      'Enter your mobile number to verify it and continue with your request',
    includeSupprotTxt: 'Support services include',
    batteryChargSupport: 'Battery charging',
    batteryManitainSupport: 'Battery maintenance',
    confirmFuelTypeMessage: 'You have selected',
    proceedWithOrder: 'Proceed with the order?',
    batteryWarentySupport: 'Battery warranty',
    tireWarentySupport: 'Tire warranty',
    agreeToTxt: 'I agree to the',
    privcymTxt: 'Privacy policy',
    userNameOnlyTextError: 'Enter Valid Username',
    andTitleTxt: 'and',
    termOfUseTxt: 'Terms of use',
    haveAnAccountTxt: 'You have an account?',
    orignalTxt: 'Orignal',
    commercialTxt: 'Commercial',
    orignalPriceTxt: 'The price of an original',
    commercialPriceTxt: 'Commercial filter price',
    priceInputTxtHold: 'Price',
    signOutTitleTxt: 'Are you sure about Sign out of the account?',
    logoutTxt: 'Logout',
    totalTxt: 'Total',
    changeTxt: 'Change',
    returnTxt: 'Return',
    orderBtnTxt: 'Order',
    appointmentTym: 'Appointment ',
    avilbleTimeSlots: 'Appointments available',
    currencyUnitsar: 'SAR',
    authErrorTitle: 'Auth Error',
    enterValidNumber: 'Enter a valid phone number',
    signUpTxt: 'Sign Up',
    imagePickError: 'Please choose the profile image on clicking user avatar',
    userNameError: 'Please enter user name',
    mobileError: 'Please enter valid mobile number',
    acceptPolicyError: 'Please accept our terms and conditions',
    userExist: 'User already exists.Please Login.',
    signUpSuccess: 'Sign Up Scuccessfull',
    signUpSucsDesc: 'Your account has been created.Please Login.',
    userDontEror: 'User does not exist.Please create account.',
    emailError: 'Please enter your valid email address.',
    loadingTxt: 'Loading...',
    productTitleEror: 'App Error',
    Appname: 'AcZurex',
    comingSoonTxt: 'This feature is coming soon!',
    // epayError:'Payment is cancelled',
    carEngineOilCapcity: 'Car Engine Oil Capcity',
    pleseEnterOilCapcity: 'Please enter your car engine oil capacity.',
    paymentCanceled: 'Payment Canceled',
    productDescEror: 'Please select atleast one product from the list.',
    productNotSelectedFlowEror:
      'You can not proceed to next step without selecting any product.',
    madeInTxt: 'Made In',
    emptyListValue: 'There are no orders',
    emptyListValueWarenty:
      'Your Cars along with warrentied products will be shown here',
    delOrderTitle: 'Are you sure you want to cancel this order?',
    userInfoProcessEror: 'Information gathering error',
    userInfoError: 'Please select a time slot for the appointment',
    paymentMethodError: 'Please Select a payment method.',
    inProgress: 'This feature is still in progress',
    optionalTxt: 'Optionals',

    minimumAmount100:
      'To use Tamara installments your order price must be greater then 100',
    yourSelectedLocationString: 'Your Selected Delivery Location',
    parcelLocation: 'Driver Location',
    carPlateNewrror:
      'Car Plate Number must be at least 4 digits and Plate Text must be separated with space and must be length 5 including spaces',
    carNameTxt: 'Car Name',
    warentyExamSelectionError:
      'Please Select Examination Now or Later option or either disable it',
    carAddErrorManual:
      'Please Fill all fields properly and Car number must be four digit and three alphabet',
    carPlateNumberError:
      'Car Plate number should be four numbers and car plate text should be three alphabets.',
    saved25SS: 'You saved 25 SAR just now',
    regTypeDescAr: 'Registration Type Description',
    vehicleIDNumber: 'Vehicle ID Number',
    make: 'Make',
    modelYear: 'Modal Year',
    modalTxt: 'Modal',
    vehicleClassDescAr: 'Vehicle Class Description',
    cylinder: 'Cylinder',
    free_services_count: 'Available Free Services',
    free_service: 'Free Service',
    book_free_service: 'Book Free Service',
    book_paid_service: 'Book Paid Service',
    book_free_service_desc: 'Click on NEXT to confirm your free service for ',
    book_paid_service_desc: 'Booking Service for ',
    orderPrice: 'Order Price ',
    noSlotsForDate: 'Sorry, no slots available for selected date.',
    paymentFailed: 'Payment Failed',
    Payment_Error: 'Payment Rejected',
    tyres_quantity: 'Select number of tyres',
  };
  const textStringArb = {
    tyres_quantity: 'اختر عدد الإطارات',
    emailAlreadyInUse: 'البريد الالكتروني قيد الاستخدام بالفعل',
    phoneAlreadyInUse: 'رقم الهاتف قيد الاستخدام بالفعل',
    invalidEmailError: 'عنوان البريد الإلكتروني غير صالح.',
    invalidVerficationCodeError: 'رمز التحقق غير صالح',
    carPlateNumberErrorAlert: 'تم العثور على رقم لوحة مكرر، تم تخطي الحفظ',
    regTypeDescAr: 'وصف نوع التسجيل',
    modalTxt: 'مشروط',
    vehicleIDNumber: 'رقم هوية المركبة',
    Payment_Error: 'تم رفض الدفع',
    make: 'يصنع',
    modelYear: 'سنة مشروطة',
    vehicleClassDescAr: 'وصف فئة السيارة',
    cylinder: 'اسطوانة',
    carPlateNumberError:
      'يجب أن يتكون رقم لوحة السيارة من أربعة أرقام ويجب أن يتكون نص لوحة السيارة من ثلاثة أحرف أبجدية.',
    productHasBeenDeleted: 'يتم الآن تحميل تفاصيل المنتج.',
    paymentCanceled: 'تم إلغاء الدفع',
    saved25SS: 'لقد وفرت 25 ريالاً سعوديًا الآن',
    carAddErrorManual:
      'يرجى ملء جميع الحقول بشكل صحيح ويجب أن يتكون رقم السيارة من أربعة أرقام وثلاثة أبجدية',
    carNameTxt: 'اسم السيارة',
    warentyExamSelectionError:
      'الرجاء تحديد خيار الفحص الآن أو لاحقًا أو تعطيله',
    carPlateNewrror:
      'يجب أن يتكون رقم لوحة السيارة من 4 أرقام على الأقل ويجب أن يكون نص اللوحة مفصولاً بمسافة ويجب أن يكون طوله 5 مع المسافات',
    yourSelectedLocationString: 'موقع التسليم الذي اخترته',
    parcelLocation: 'موقع السائق',
    minimumAmount100: 'لاستخدام أقساط تمارا، يجب أن يكون سعر طلبك أكبر من 100',
    optionalTxt: 'خيارات',
    inProgress: 'هذه الميزة لا تزال قيد التقدم',
    orderStatusCanceled: 'ألغيت',
    invalidPhoneNumberError: 'رقم الهاتف يجب أن يكون 9 أرقام.',
    paymentMethodError: 'الرجاء اختيار طريقة الدفع.',
    userInfoError: 'الرجاء تحديد فترة زمنية للموعد',
    userInfoProcessEror: 'خطأ في جمع المعلومات',
    delOrderTitle: 'هل أنت متأكد أنك تريد إلغاء هذا الطلب؟',
    emptyListValue: 'لا توجد أوامر',
    emptyListValueWarenty: 'سيتم عرض سياراتك مع المنتجات الخاضعة للضمان هنا',
    madeInTxt: 'صنع في',
    productTitleEror: 'خطأ في التطبيق',
    carEngineOilCapcity: 'سعة زيت محرك السيارة',
    pleseEnterOilCapcity: 'الرجاء إدخال سعة زيت محرك سيارتك.',
    productDescEror: 'الرجاء تحديد منتج واحد على الأقل من القائمة.',
    ComingSoon: 'قريباً !',
    comingSoonTxt: 'هذه الميزة قادمة قريبا!',
    productNotSelectedFlowEror:
      'لا يمكنك المتابعة إلى الخطوة التالية دون تحديد أي منتج',
    loadingTxt: 'تحميل...',
    emailError: 'الرجاء إدخال عنوان البريد الإلكتروني الخاص بك.',
    userDontEror: 'المستخدم غير موجود.يرجى إنشاء حساب.',
    signUpSuccess: 'الاشتراك بنجاح',
    signUpSucsDesc: 'لقد تم إنشاء حسابك. الرجاء تسجيل الدخول.',
    userExist: 'المستخدم موجود بالفعل. الرجاء تسجيل الدخول.',
    tabbyOrderHighError:
      'قيمة الطلب تفوق الحد الأقصى المسموح به حاليًا مع تابي. يُرجى تخفيض قيمة السلة أو استخدام وسيلة دفع أخرى.',
    tabbyTooLowError:
      'قيمة الطلب أقل من الحد الأدنى المطلوب لاستخدام خدمة تابي. يُرجى زيادة قيمة الطلب أو استخدام وسيلة دفع أخرى.',
    tabbyNoEnoughLimit: 'ليس لديك الحد الكافي لإكمال هذه الدفعة.',
    acceptPolicyError: 'يرجى قبول الشروط والأحكام لدينا',

    imagePickError:
      'الرجاء اختيار صورة الملف الشخصي عند النقر على الصورة الرمزية للمستخدم',
    userNameError: 'الرجاء إدخال اسم المستخدم',
    mobileError: 'الرجاء إدخال رقم الجوال',
    signUpTxt: 'الاشتراك',
    enterValidNumber: 'أدخل رقم هاتف صالحًا',
    authErrorTitle: 'خطأ مصادقة',
    currencyUnitsar: 'ر.س',
    avilbleTimeSlots: 'المواعيد المتاحة',
    orderBtnTxt: 'الطلبات',
    returnTxt: 'رجوع',
    changeTxt: 'تغيير',
    totalTxt: 'الإجمالي',
    logoutTxt: 'تسجيل خروج',
    signOutTitleTxt: 'هل أنت متأكد من أنك تريد تسجيل خروج من الحساب',
    priceInputTxtHold: 'سعر',
    orignalPriceTxt: 'سعر الأصل',
    commercialPriceTxt: 'السعر التجاري',
    commercialTxt: 'تجاري',
    orignalTxt: 'أصلي',
    userNameOnlyTextError: 'أدخل اسم مستخدم صالح',
    haveAnAccountTxt: 'عندك حساب؟',
    termOfUseTxt: 'شروط الاستخدام',
    andTitleTxt: 'و',
    privcymTxt: 'الخصوصية',
    agreeToTxt: 'أوافق على سياسة',
    batteryChargSupport: 'شحن البطارية',
    batteryManitainSupport: 'صيانة البطارية',
    batteryWarentySupport: 'ضمان البطارية',
    tireWarentySupport: 'ضمان الاطارات',
    includeSupprotTxt: 'الخدمات المساندة تشمل',
    tamarMobileVerfSub: 'أدخل رقم جوالك للتحقق منه والاستمرار بطلبك',
    tamareaLoginTxt: 'تسجيل الدخول أو انشاء حساب جديد',
    gettinHelpTxt: 'احصل على المساعدة',
    UnVerifcationConfirmedTitle: 'تم رفض طلب التحقق',
    UnVerifcationConfirmedSubTitle:
      'لم تكتمل عملية التحقق بنجاح , يرجى إعادة محاولة عملية التحقق لاحقاً',
    verifcationConfirmedTitle: 'تم تأكيد الطلب',
    verifcationConfirmedSubTitle: 'اكتملت عملية التحقق بنجاح',
    tiresDescTxt: 'الشركة المصنعة',
    singleTireTxt: 'اطار',
    rimTxt: 'الجنط',
    yesSureTxt: 'نعم أنا متأكد',
    yesTxtLog: 'نعم',
    noTxtLog: 'لا',
    attentionTxtLog: 'انتباه',
    noFiltersFoundTxt: 'لا توجد مرشحات متاحة لسيارتك',
    oilAttentionTxt:
      'حاليا نقدم خدمة التوصيل فقط في الرياض. للمتابعة، يرجى النقر على "نعم".',

    delAccountTitleTxt: 'هل أنت متأكد من حذف الحساب',
    deleteAccountTxt: 'حذف الحساب',
    languagNameTxt: 'العربية',
    languageTxt: 'اللغة',
    notificationTxt: 'الاشعارات',
    settingHedTxt: 'الاعدادات',
    termConditionTxt: 'الشروط والأحكام',
    termsdataTxt: [
      {
        answer:
          ' يحتفظ المتجر بالحق في تغيير أجزاء من شروط الاستخدام والأحكام أو تعديلها أو إضافة البعض منها، أو إزالتها في أي وقت من الأوقات، وتصبح التغييرات فعالة عندما يتم نشرها على المتجر من دون سابق إنذار، لذا نأمل منك مراجعة الشروط و الأحكام بشكل دوري لمواكبة كل التحديثات ',
        id: 0,
      },
      {
        answer: 'بياناتك الشخصية وخصوصياتك لدينا في سرية تامة وهي محل اهتمامنا',
        id: 1,
      },
      {
        answer:
          'المداومة على تحديث بياناتك ومعلوماتك بشكل   مستمر أثناء عملية الشراء بما فيها عنوان البريد   ورقم بطاقتك الائتمانية وتواريخها حتى نستطيع  استكمال عملياتك الشرائية على المتجر والتواصل  .معك عند الحاجة لذلك',
        id: 2,
      },
      {
        answer:
          ' المتجر له الحق أن يقوم بسحب عضوية أو تعليق  حساب العملاء المخالفين لأي بند من بنود الإستخدام',
        id: 3,
      },
      {
        answer: 'لا يحق لأي شخص أن يقوم بالتسجيل كعضو في المتجر أكثر من مرة  ',
        id: 4,
      },
      {
        answer:
          'لإتمام عملية التسجيل لابد من توفير كافة معلومات الاتصال الخاصة بك',
        id: 5,
      },
      {
        answer: 'لا تتم عملية البيع إلا في حالة قبولك للشروط ',
        id: 6,
      },
      {
        answer:
          'الموافقة على تقبل المسئولية عن جميع العمليات  .التي تتم تحت الحساب الخاص بك ورقمك السري',
        id: 7,
      },
      {
        answer:
          ' نسعى جاهدين لتوفير كافة المعلومات بشأن تسعير المنتجات وتوفير وصف دقيق عن كل منتج  .من المنتجات المعروضة في المتجر',
        id: 8,
      },
      {
        answer:
          'قد تكون مسئول مسئولية كاملة أمام الجهات المختصة والقضائية حال ثبت أنك تستخدم بريد الكتروني مضلل أو زائف أو تنتحل شخصية أخرى بغرض التضليل لنا حتى لا نعرف مصدر',
        id: 9,
      },
      {
        answer:
          'أي من تعليقاتك أو تقوم بنشر محتويات مخالفة  أو فيروسات أو برمجيات خبيثة قد تضر بالمتجر',
        id: 10,
      },
      {
        answer:
          'فإنه يحق لنا في حال انتهاكك لأي بند من البنود  السابقة إيقاف استخدامك للمتجر',
        id: 11,
      },
    ],
    tipsAndArticleTxt: 'نصائح ومقالات',
    replaceTimeTopHeadTxt: 'كيف تعرف أن بطارية سيارتك حان وقت استبدالها؟',
    tip7HotHeadTxt: '7 نصائح للحفاظ على بطارية سيارتك في الطقس الحار',
    secret10TxtHead: '10 أسرار يجب على كل امرأة معرفتها قبل شراء سيارة جديدة',
    resons9TxtHead: '9 أسباب لتوقف بطارية سيارتك عن العمل فجأة',
    firstartcle: [
      {
        id: 0,
        question: 'الشحن الزائد للبطارية',
        answer:
          'يؤدي الشحن الزائد للبطارية إلى توقفها المفاجئ  عن العمل وتلفها، لذلك عليك الحذر والتأكد من حالة منظم الكهرباء إذا كان يعمل بشكل جيد أو كان معطلاً أو هناك خطأ في ضبطه، لأن كل ما سبق ذكره يؤدي إلى زيادة الشحن في البطارية وبالتالي تحلل وتآكل الألواح داخلها مما يفقدها .قوتها ويعرضها للتلف     ',
      },
      {
        id: 1,
        question: 'عدم شحن البطارية بشكل كامل',
        answer:
          'تسبب الأعطال في منظومة السيارة الكهربائية أو عدم ضبطها بشكل جيد، بالإضافة إلى ارتخاء  سير المروحة بالسيارة إلى عدم شحن البطارية بشكل كامل، والأمر لا ينتهي هنا لأن ذلك يؤدي إلى تكوين طبقة من الأملاح على ألواح البطارية تضعف أداءها وتعرضها للتلف خاصة إذا لم يعالج الخلل سريعاً',
      },
      {
        id: 2,
        question: 'تآكل واتساخ أقطاب البطارية بالسيارة',
        answer:
          'عليك الانتباه جيداً لحالة الكابلات وربطها بإحكام مع أطراف البطارية والتأكد من نظافتها وخلوها من الأعطال المقاومة عند الأطراف وبالتالي تقل كفاءة شحن البطارية، ومن ثم يقل فرق الجهد المطلوب لتشغيل .محرك السيارة   , لأن أي خلل في ذلك يؤدي إلى زيادة ',
      },
      {
        id: 3,
        question: 'عدم تثبيت البطارية بإحكام داخل السيارة ',
        answer:
          'ذلك يعرضها للاهتزاز وبالتالي تساقط المادة الفعالة وتسربها من ألواح البطارية، إضافة إلى التسبب في سر اللحام الواصل بين خلايا البطارية, مما يؤدي الى تلف البطارية وتوقفها عن العمل',
      },
      {
        id: 4,
        question: 'المبالغة في إحكام توصيل وتثبيت البطارية',
        answer:
          'يمكن أن يؤدي إلى تضرر صندوق البطارية وحدوث كسر أو شق فيه، وبالتالي تسرب المادة من البطارية والتي تؤدي إلى تلفها وتلف الأجزاء الأخرى ',
      },
      {
        id: 5,
        question: 'تعطل محرك السيارة',
        answer:
          ' إشارة واضحة لتشخيص تلف البطارية ومؤشر قوي على ضعفها، كما أنه عند تعرض المحرك  لأي عطل فإن كثرة محاولات تشغيل المحرك تؤدي إلى  استنفاذ البطارية مما يؤدي إلى تلفها ',
      },
      {
        id: 6,
        question: 'كثرة التوقف المفاجئ للسيارة أثناء السير',
        answer:
          'توقف السيارة فجأة عن العمل قد يكون السبب في  ذلك تلف البطارية أو جودة المولد الرديئة أو مضخة الوقود  من ثلاث مرات في الأسبوع فأغلب الظن أن الوقت  حان لشراء بطارية جديدة   , ولأجل هذا إذا تكرر توقف السيارة فجأة أكثر',
      },
      {
        id: 7,
        question: 'موعد تغيير بطارية السيارة',
        answer:
          'كل بطارية لديها عمر افتراضي معين وعليك الانتباه إلى الوقت المناسب لتغيير البطارية، إذ أنه ليس عليك الانتظار لحين تلفها بالكامل بل يمكنك ملاحظة المؤشرات التي تخبرك بالوقت المثالي لذلك حتى تتجنب أعطال البطارية المفاجئة',
      },
      {
        id: 8,
        question: 'مشاكل في السيارة على فترات متقطعة',
        answer:
          'إذا لاحظت أن سيارتك تعمل بشكل جيد اليوم وفي اليوم التالي تعاني من مشكلة وهكذا استمر الأمر فهذه علامة على أن البطارية فيها خطب ما, مثل أن تكون مكسورة أو أطرافها متآكلة أو تعاني من التكلس , لأجل هذا يجب التحقق من حالتها',
      },
    ],
    secondarticle: [
      {id: 0, answer: 'ابدئي البحث بشكل جيد'},
      {id: 1, answer: 'اختاري الوقت المناسب '},
      {id: 2, answer: 'التركيز على السعر وليس المدفوعات'},
      {id: 3, answer: 'فكري في لون السيارة '},
      {id: 4, answer: 'تأكدي من فحص السيارة عند الخبير'},
      {id: 5, answer: 'فكري في حجم السيارة المناسب '},
      {id: 6, answer: 'اختاري سيارة يمكن التعامل معها دونتعقيد'},
      {id: 7, answer: 'ابتعدي عن السيارات الرياضية لمحركاتها القوية'},
      {id: 8, answer: 'فكري في الصيانة'},
      {id: 9, answer: 'من الممكن التفكير في السيارة المستعملة'},
    ],
    fortharticle: [
      {
        id: 0,
        answer:
          '.صعوبة تشغيل محرك السيارة، إذ أنك  ستلاحظ أن تشغيل السيارة يتطلب وقتاً ومحاولات عديدة',
      },
      {
        id: 1,
        answer:
          'إضاءة علامة البطارية في لوحة القيادة مؤشر لا لا يجب عليك تجاهله , في معظم الأحيان تشير الى مشكلة في نظام الشحن أو تلف البطارية',
      },
      {
        id: 2,
        answer:
          'ظهور انتفاخ في البطارية وتشوه شكلها, وهذا يحدث نتيجة الشحن الزائد للبطارية',
      },
      {
        id: 3,
        answer:
          'تسرب السائل من البطارية، حيث تميل البطاريات السائلة إلى تسرب الحمض نتيجة الشحن الزائد أو التلف وبكل الأحوال عند حدوث ذلك عليك .استبدالها في الحال',
      },
    ],
    thirdarticle: [
      {id: 0, answer: ' تجنب الرحلات القصيرة والقيادة لمسافات قريبة'},
      {
        id: 1,
        answer: ' تأكد من إطفاء الأضواء الداخلية والخارجية عند مغادرة السيارة',
      },
      {id: 2, answer: 'حافظ على نظافة البطارية والأسلاك باستمرار'},
      {
        id: 3,
        answer:
          'تجنب استخدام الأجهزة الإلكترونية مثل الراديو  عند إيقاف محرك السيارة',
      },
      {
        id: 4,
        answer: ' اركن سيارتك في الظل أو في المرأب لحمايتها',
      },
      {id: 5, answer: 'تأكد من أن العازل الحراري ثابت في مكانه'},
      {
        id: 6,
        answer:
          'انتبه للمؤشرات التي تخبرك أن بطارية سيارتك .فيها مشكلة ما أو تحتاج إلى الصيانة ',
      },
    ],
    bridgeStoneTireTxt: 'اطار بريدجستون',
    michlanTireTxt: 'اطار ميشلان',
    madeInFrance: 'بلد الصنع فرنسا',
    madeInJapan: 'بلد الصنع اليابان',
    time: 'سنوات فقط',
    yearsOnlyTxt: 'سنوات فقط',
    saveBtnTxt: 'حفظ',
    userNameTxt: 'اسم المستخدم',
    myProfileTxt: 'الملف الشخصي',
    plateplaceTxt:
      'قم بإدخال الأحرف، سواء العربية أو الإنجليزية، من اليسار إلى اليمين.',
    payMethodTxt: 'طرق الدفع',
    orderStatusTxt: 'حالة الطلب',
    payCompletSuccess: 'اكتمل الدفع بنجاح',
    completeThePayTxt: 'أكمل الدفع',
    rateServiceProviderTxt: 'يرجى تقييم مزود الخدمة',
    serviceProvidedTxt: 'كيف تم تقديم الخدمة من قبلنا؟',
    goNowBtnTxt: 'اذهب الآن',
    noBtnTxt: 'لاحقاً',
    rateUsStoreTxt: 'يرجى تقييمنا في المتجر',
    cancelTxt: 'الغاء',
    rateUsTxt: 'تقييم الطلب',
    recepiantAddressTxt: 'موقع المستلم',
    orderTimeTxt: 'وقت الطلب',
    quantityTxt: 'الكمية',
    orderCompletedTxt: 'تم الانتهاء من طلبك',
    orderOnWayTxt: 'الطلب في الطريق اليك',
    weRcevedOrderTxt: 'استلمنا طلبك',
    fuelTypeTxt: 'نوع الوقود',
    trackingOrderTxt: 'تتبع الطلب',
    homeBtnTxt: 'الرئيسية',
    loremTxt: 'شكرًا لك على تقديم الطلب مع\nZurex',
    oilOfferNotIncludedTxt: 'لا يشمل العرض',
    oilOfferIncludedTxt: 'استرداد نقدي 10٪ + غسيل مجاني',
    oilNameSelectTitle1: 'زيت زيوركس',
    oilNameSelectTitle2: 'زيت شل',
    oilNameSelectTitle3: 'زيت كاسترول',
    oilNameSelectTitle4: 'زيت موبيل ',
    petrol: 'بنزين',
    diesel: 'ديزل',
    airConditionerFilterTxt: 'فلتر مكيف',
    back: 'خلف',

    airFilterTxt: 'هواء فلاتر',
    oilFilterTxt: 'زيت فلاتر',
    typeOfOilTxt: 'نوع الزيت ',
    selctFilterType: 'الرجاء تحديد نوع الفلتر',
    tabbyGeneralError:
      'عذرًا، تابي غير قادر على الموافقة على عملية الشراء هذه. الرجاء استخدام طريقة دفع بديلة لطلبك.',
    numberOfOilRefills: 'عدد عبوات الزيت',
    orderStatusComplete: 'مكتمل',
    orderStatusPanding: 'قيد الانتظار',
    orderStatusApproved: 'تمت الموافقة',
    selectFuelTypeError: 'الرجاء تحديد نوع الوقود',
    confirmFuelTypeMessage: 'قمت بتحديدها',
    currentBtnTxt: 'الحالية',
    comingBtnTxt: 'تحت المعالجة',
    perviosBtnTxt: 'مكتمل',
    folowUpPayTxt: 'متابعة الدفع',
    oilTxt: 'زيوت',
    oilListTxt: 'قائمة الزيوت',
    batteryListTxt: 'قائمة البطاريات',
    anOtherReqTxt: 'إضافة الي السلة',
    addToCartTxt: 'إضافة الي السلة',
    transferTxt: 'نقل',
    privateTxt: 'خصوصي',
    manualEnteryTxt: 'ادخال يدوي',
    plateNumTxt: 'رقم اللوحة',
    successFullTxt: 'ناجح!',
    carDataUpdatedDone: 'تم تحديث بيانات السيارات بنجاح',
    chooseMethodTxt: 'الرجاء اختيار إحدى الطرق أدناه\nلإدخال بيانات سيارتك',
    myCarBilltitle1: 'زيت غسيل المكينة',
    myCarBilltitle2: 'زيت فرامل',
    myCarBilltitle3: 'زيت دريكسون',
    myCarBilltitle4: 'زيت جير',
    myCarBilltitle5: 'ماء رديتر',
    dontAccount: 'ليس لديك حساب؟',
    createTxt: 'إنشاء حساب',
    loginBtnTxt: 'تسجيل دخول',
    loginInputFieldTxt1: 'رقم الجوال',
    reSendTxt: 'إعادة الارسال',
    verfCode: 'كود التحقق',
    enterVerfChangNum: 'تغيير رقم الجوال',
    enterVerfSubTxt:
      '  قمنا بارسال رسالة نصية تتضمن رمز تحقق مكون من 4 أرقام لرقم جوالك ',
    enterVerfCodeTxt: 'أدخل رمز التحقق',
    idVerificationTitle: 'التحقق من الهوية الخاصة بك',
    verfIdSubTxt:
      ' يرجى ادخال رقم الهوية الخاص بك لمتابعة عملية التحقق يرجى التأكد من ادخال رقم الهوية المرتبط برقم الجوال',
    verfIdSubTxt1:
      ' سيتم استخدام هذه المعلومات لتوثيق هويتك حسب ما نصت عليه تعاليم البنك السعودي المركزي',
    lernMoreTxt: 'لمعرفة المزيد',
    resdNumTxt: 'ID / residence number',
    followUpTxt: 'المتابعة',
    vIdModelMainTxt: 'تأكد من تحميل وتفعيل تطبيق Nafath',
    vIdModelSubTxt:
      ' للتحقق من هويتك واكمال عملية الدفع باستعمال تمارا يرجى التأكد من توافر تطبيق نفاذ',
    vIdModelbtn1Txt: 'المتابعة لعملية التحقق',
    vIdModelbtn2Txt: 'تحميل تطبيق نفاذ',
    waitTitleTxt: " يرجى الانتظار بعض {'\n'}الوقت حتى يعمل",
    validWarntyBtnTxt: 'صلاحية الضمان سارية',
    inValidWarntyBtnTxt: 'صلاحية الضمان منتهية',
    serviceDateTxt: ' تاريخ الخدمة',
    orderIDTxt: 'رقم الطلب',
    serviceDateImpltTxt: 'تاريخ تنفيذ الخدمة',
    oilFilterTitleTxt: 'الزيت والفلاتر',
    tiresTitleTxt: 'الاطارات',
    filtersNameTxtHead: 'المرشحات',
    supportSrviceHomeSubTxt: '(الضمان والاشتراك)',
    faqTitleTxt: 'الأسئلة الشائعة',
    faqQuestion1: 'ما أنواع البطاريات التي نوفرها؟',
    faqAnswer1:
      'نحن نقدم جميع أنواع بطاريات أي سي زيوركس صناعة ماليزية تدوم لمدة عام كامل حيث أننا  أننا الوكيل الحصري لهذه الماركة في المملكة العربية السعودية  ',
    faqQuestion2: 'ماذا عن جودة البطاريات؟',
    faqAnswer2:
      'جميع المنتجات التي نبيعها تلبي المتطلبات التي وضعتها دولة المملكة العربية السعودية ذات الصلة  ',
    faqQuestion3: 'لماذا يوجد اختلاف كبير في الأسعار؟',
    faqAnswer3: 'الفرق يرجع إلى جودة ونوعية البطاريات',
    faqQuestion4: 'كيف يمكنني شراء بطارية من متجراي سي زيوركس؟',
    faqAnswer4:
      'قم بدخول بياناتك على المتجر ثم اختار البطارية المفضلة إلى قائمة السلة ثم قم بتعبئة بيانات  الدفع وسيتم التواصل معك وارسال البطارية إلىمكانك مع فريق التركيب الخاص بنا ',
    faqQuestion5: 'هل البطارية تحت الضمان؟',
    faqAnswer5:
      '.تأتي كل بطارية مع ضمان قياسي  الضمان باطل إذا تم استخدام البطارية بطريقة غير مستحسنة ',
    faqQuestion6: 'هل يمكنني شراء بطارية منكم وشحنها إلى دولتي؟',
    faqAnswer6:
      'نعم يمكننا شحن لك كمية كبيرة عبر شركات الشحن الخاص بك ارجو تواصل معنا عبر البريد الالكتروني أو الدعم الفني',
    faqQuestion7: 'هل يوجد استرجاع واستبدال؟',
    faqAnswer7:
      'لا يوجد استرجاع واستبدال كرت الضمان المرفق مع البطارية ، لكن فقط حسب',
    faqQuestion8: 'هل يمكن استبدال بطارية سيارتي القديمة ببطارية اي سي زيوركس؟',
    faqAnswer8:
      'نعم، يمكنك استبدال بطاريتك ببطارية من اي سي زيوركس مع خصم 30 ريال على كود',
    whatsappTxt: 'الواتس اب',
    Snapchat: 'سناب شات',
    tiktokTxt: 'تك توك',
    instagramTxt: 'انستاغرام',
    twitterTxt: 'تويتر',
    emailTxt: 'البريد الالكتروني',
    noResultsFound: 'لم يتم العثور على نتائج بحث',
    mobileTxt: 'الموبايل',
    contactUsDescTxt:
      ' اتصل بنا بإحدى هذه الطرق وسنبذل قصارى جهدنا للرد على استفساراتك في أسرع وقت ممكن',
    confirmCarDataTxt: 'تأكيد صحة بيانات السيارة',
    seventhCategoryTxt: 'الفئة السابعة',
    carCategoryTxt: 'الفئة',
    carPlateTxt: 'اللوحة',
    nextTxt: 'التالي',
    contactUsTxt: 'تواصل معنا',
    curntLocationTxt: 'موقعك الحالي',
    openGpsSetting: 'فتح إعدادات GPS',
    gpsDisabled: 'تم تعطيل نظام تحديد المواقع. يرجى تمكينه في الإعدادات.',
    locationPermissionDenied:
      'تم رفض إذن تحديد الموقع. يرجى تمكينه في الإعدادات.',
    selectLocationTxt: 'تحديد موقع على الخارطة',
    aboutUsQuestion1: 'من نحن',

    aboutUsAnswer1:
      'تطبيق Zurex هو تطبيق شامل لشركة إسماعيل الجمان الحمراني للتجارة، الرائدة في مجال بطاريات السيارات، إطارات السيارات واستيراد قطع غيار السيارات وإكسسواراتها على مستوى المملكة العربية السعودية. تمتد أنشطتنا وخدماتنا إلى نطاق واسع في جميع أنحاء المملكة من خلال فروعنا. نحن الوكيل الحصري لعلامتي AC ZUREX وCAMEL في المملكة.',

    aboutUsQuestion2: 'خدماتنا',
    aboutUsAnswer2:
      'نعمل في شركة إسماعيل الجمان الحمراني للتجارة على تقديم أفضل أنواع بطاريات السيارات، إطارات السيارات، قطع الغيار والإكسسوارات لجميع عملائنا بالجودة المطلوبة. نحن من رواد موزعي مختلف العلامات التجارية من البطاريات والإطارات من كوريا، تايوان، إندونيسيا، تايلاند، الصين، وصناعة محلية.',

    aboutUsQuestion3: 'رؤيتنا',
    aboutUsAnswer3:
      'تهدف المؤسسة إلى أن تكون الرائدة في مجالها في تجارة الجملة والتجزئة لمنتجات السيارات وقطع الغيار والإكسسوارات، وبيع بطاريات وإطارات السيارات والشاحنات عالية الجودة في المملكة. وتسعى لتحقيق رؤيتها من خلال النمو المستدام عبر الابتكار في التطوير والازدهار مع أفضل المنتجات العالمية وتوفير قوة عاملة متقدمة من المهندسين والمستشارين.',

    aboutUsQuestion4: 'أهدافنا',
    aboutUsAnswer4:
      'تقديم أفضل المنتجات ذات الجودة العالية وخدمات ما بعد البيع الفعالة على المستوى الوطني، ونعمل على تطويرها بالتوازي مع الأسواق المحلية والدولية بمنتجات عالية الجودة وصديقة للبيئة وبضمان. رضا العملاء هو هدف شركتنا، ونسعى باستمرار للوصول إلى الأسواق العالمية واستكشافها',

    aboutUsQuestion5: 'Our Values ',
    aboutUsAnswer5:
      'الثروة الحقيقية للشركة تكمن في علاقاتها الراسخة. نعتبرها الركيزة الأساسية في بناء وإدارة شركتنا، وهي من الثوابت التي لا نحيد عنها، ونسعى لفهم متطلبات واحتياجات عملائنا.',
    btnLess: 'تظهر أقل',
    btnMore: 'المزيد',
    myCars: 'سياراتي',
    carsTxt: 'سيارات',
    addACar: 'اضافة سيارة',
    locationTxt: 'الموقع',
    timeTxt: 'الوقت',
    confirmationTxt: 'تأكيد الطلب',
    chooseDateTxt: 'التاريخ',
    chooseTimeTxt: 'الوقت',
    riyazTxt: 'الرياض',
    addCar: 'إضافة سيارة',
    selectCarType: 'اختر اسم السيارة',
    selectCarCatg: 'مصنع سيارات',
    selectCarModal: 'طراز السيارة',
    writePlateNumber: 'اكتب رقم اللوحة',
    writePlateTxt: 'اكتب نص اللوحة',
    myOrder: 'طلباتي',
    addWarentytxt: 'اضافة خدمة الفحص والاشتراك والضمان',
    now100: '100 الآن',
    later125: '125 لاحقاً',
    save25: '25 وفر',
    priceTxt: 'السعر',
    wagesTxt: 'رسوم الخدمات',
    taxTxt: 'الضريبة',
    discountTxt: 'كود الخصم',
    appointmentTym: 'التعيين',
    cashbackTxt: 'الكاش باك',
    completeOrder: 'اكتمال الطلب',
    completeOrder2: 'اتمام الدفع',
    orderSuccess: 'تم الطلب بنجاح',
    balanceTxt: 'الرصيد',
    balanceSubTxt: '(الكاش باك)',
    supportTxt: 'الخدمات المساندة',
    supportSubTxt: '(شحن بطارية وضمان)',
    currencyTxt: 'ر.س',
    requestTxt: 'طلب',
    batteryTxt: 'البطاريات',
    singleBatteryTxt: 'بطارية',
    descriptionTxt: 'الوصف',
    itemNoTxt: 'رقم الصنف',
    ePayTxt: 'الدفع الالكتروني',
    installTxt: 'شركات التقسيط',
    cashPayTxt: 'الدفع عند الاستلام',
    ampereTxt: 'أمبير',
    lengthTxt: 'الطول',
    widthTxt: 'العرض',
    heightTxt: 'الارتقاع',
    camelBatteryDescTxt: 'بطارية سيارة الكترونية صناعة صينية',
    totalHeightTxt: 'الارتفاع الاجمالي',
    coolEngyTxt: 'تدوير طاقة بارد',
    chooseBateryTxt: 'اختر نوع البطارية',
    proceedWithOrder: 'المضي قدما في الطلب؟',
    chooseTireTxt: 'حدد نوع الإطارات',
    acZurexBatteryTxt: 'بطارية ايه سي زيوركس',
    camelBatteryTxt: 'بطارية كمل',

    n100BatteryDescTxt:
      'بطارية سيارة إلكترونية مصنوعة في ماليزيا ولا تتطلب صيانة',
    free_services_count: 'الخدمات المجانية المتاحة',
    free_service: 'خدمة مجانية',
    book_free_service: 'حجز الخدمة المجانية',
    book_paid_service: 'حجز الخدمة المدفوعة',
    book_free_service_desc: 'انقر على التالي لتأكيد الخدمة المجانية الخاصة بك',
    book_paid_service_desc: 'خدمة الحجز ل',
    orderPrice: 'سعر الطلب ',
    noSlotsForDate: 'عذرًا، لا توجد فتحات متاحة للتاريخ المحدد.',
    paymentFailed: 'عملية الدفع فشلت',
  };

  const {isArabicLanguage} = useSelector(state => state.auth);
  const textStrings = isArabicLanguage ? textStringArb : textStringEng;

  return {textStrings};
};
