import {StyleSheet} from 'react-native';
import {w, h} from 'react-native-responsiveness';
import {c0color, redcolor, textcolor, maincolor} from '../assets/Colors';
import {scale} from 'react-native-size-matters';

const TextStyles = StyleSheet.create({
  appbtntxt: {
    fontSize: scale(16),
    color: 'white',
    fontWeight: '400',
    textTransform: 'capitalize',
  },
  choiceinputmainbtndivseltxt: {
    width: '72%',
    lineHeight: h('3%'),
    fontSize: scale(14),
    marginLeft: w('2%'),
    color: 'rgba(0,0,0,0.7)',
  },
  choiceinputbtntxt: {
    fontSize: scale(14),
  },
  choiceinputinputxthead: {
    fontSize: scale(16),
    color: 'black',
    width: '100%',
  },
  Myorderbtntxt: {
    fontSize: scale(16),
  },
  verifcationcodesentdesc: {
    color: textcolor,
    fontSize: scale(16),
    fontWeight: '400',
    width: '100%',
    alignSelf: 'center',
    marginBottom: h('1%'),
  },
  custombtntitletxt: {
    fontSize: scale(16),
    fontWeight: '400',
  },
  waitscreentxt: {
    fontSize: scale(20),
    color: 'black',
    fontWeight: '400',
    textAlign: 'center',
    marginTop: h('5%'),
  },
  verificationCodemainhed: {
    color: maincolor,
    marginBottom: h('2%'),
    fontSize: h('2.7%'),
    fontWeight: '400',
    width: '90%',
    alignSelf: 'center',
  },
  ordercompletemaintxt: {
    fontSize: scale(20),
    color: 'black',
    marginVertical: h('3%'),
  },
  ordercompletemaintxt1: {
    fontSize: scale(15),
    color: 'black',
    marginVertical: h('3%'),
  },
  ordercompletesubtext: {
    width: '70%',
    textAlign: 'center',
    fontSize: scale(14),
    marginBottom: h('14%'),
  },
  verficationchangenumber: {
    color: maincolor,
    fontSize: scale(12),
    fontWeight: '400',
    textDecorationLine: 'underline',
    textDecorationColor: maincolor,
  },
  dropdownlistoiltxt: {
    color: 'black',
    fontSize: scale(20),
    fontWeight: '400',
  },
  newcurvedscreenname: {
    fontSize: scale(20),
    fontWeight: '400',
    color: 'white',
  },
  paymentcompletetxt: {
    color: 'black',
    marginBottom: h('1.5%'),
    fontSize: scale(20),
    fontWeight: '400',
    marginTop: h('7%'),
  },
  verificationtxt: {
    color: 'black',
    fontSize: scale(20),
    fontWeight: '400',
    marginBottom: h('3%'),
  },
  verificationsubtxt: {
    color: textcolor,
    fontSize: scale(14),
    fontWeight: '400',
    marginBottom: h('0.7%'),
    textAlign: 'center',
    width: '76%',
  },
  fwbold: {fontWeight: 'bold'},
  orderstepstimetxt: {
    color: textcolor,
    fontSize: scale(16),
  },
  ordercalctaxname: {
    color: 'black',
    fontSize: scale(16),
  },
  orderdetaillocationHeadingtitle: {
    width: '90%',
    fontSize: scale(12),
    color: 'black',
  },
  verificationresendtxt: {
    color: maincolor,
    fontSize: scale(16),
    fontWeight: '400',
    textDecorationLine: 'underline',
    textDecorationColor: maincolor,
  },
  orderdetaillocationtitle: {
    fontSize: scale(14),
    color: 'black',
    width: '94%',
    alignSelf: 'center',
  },
  tiresselectmainheadingtxt: {
    width: '80%',
    fontSize: scale(16),
    color: 'black',
    fontWeight: '600',
    marginTop: h('3.5%'),
    alignSelf: 'flex-start',
    textAlign: 'left',
  },
  rattinHeadintxt: {
    fontSize: scale(16),
    color: 'black',
    marginBottom: h('1%'),
  },
  contactscreenmainHeading: {
    width: '90%',
    alignSelf: 'center',
    marginBottom: h('5%'),
    fontSize: scale(14),
    color: 'black',
  },
  addoilreqmainbtndivseltxt: {
    width: w('79%'),
    lineHeight: h('3%'),
    fontSize: scale(16),
    color: 'rgba(0,0,0,0.5)',
    //marginTop: h('2%'),
  },
  confirmcardatamainbtndivseltxt: {
    width: w('79%'),
    lineHeight: h('3%'),
    fontSize: scale(16),
    textAlign: 'left',
  },
  addoilsmallborderdivtext: {
    color: maincolor,
    fontSize: scale(16),
  },
  aboutanswertxt: {color: textcolor, fontSize: scale(16)},
  aboutquestiontxt: {
    fontWeight: '900',
    color: maincolor,
    fontSize: scale(20),
  },
  sidenavebtntxt: {fontSize: scale(16), color: 'black'},
  bottomtabbtntxtCont: {
    fontSize: scale(14),
  },
  orderstepsdesctxt: {
    color: 'black',
    fontSize: scale(16),
    fontWeight: '400',
  },
  newheaderimfscreenname: {
    fontSize: scale(20),
    fontWeight: '400',
    color: 'white',
  },
  lineedbtnbtntxt: {
    fontSize: scale(16),
  },
  tiresselectfilltxtspae: {
    width: '85%',
    height: '100%',
    fontSize: scale(14),
    color: 'black',
    textAlign: 'left',
  },
  tireselectsubheadingtxt: {
    width: '80%',
    fontSize: scale(14),
    color: textcolor,
    fontWeight: '400',
    marginTop: h('1%'),
    alignSelf: 'flex-start',
    textAlign: 'left',
  },
  linedbtnmainbtndivseltxt: {
    width: '72%',
    lineHeight: h('3%'),
    fontSize: scale(14),
    marginLeft: w('2%'),
    color: 'black',
  },
  faqcompanstxt: {fontSize: scale(16), color: textcolor},
  faqcompquesttxt: {fontSize: scale(16), color: 'black'},
  customdropdownvaluetxt: {
    color: 'black',
    fontSize: scale(14),
  },
  tamaralogininputtxt: {
    color: textcolor,
    marginBottom: h('1.5%'),
    fontSize: scale(16),
    fontWeight: '400',
    alignSelf: 'center',
    width: '90%',
  },
  supportmainheadingtxt: {
    width: '90%',
    marginTop: h('2%'),
    alignSelf: 'center',
    color: 'black',
    fontSize: scale(20),
  },
  completesteptxt: {
    width: '100%',
    textAlign: 'center',
    marginTop: h('1%'),
    fontSize: h('2%'),
  },
  verifCodeScreentxt: {
    fontSize: scale(16),
    color: textcolor,
  },
  customDropdowntitletxt: {
    fontSize: scale(14),
    fontWeight: '400',
  },
  drwerlogouttxt: {
    fontSize: scale(16),
    marginLeft: 5,
    color: redcolor,
  },
  profilenamedrawertxt: {
    fontSize: scale(16),
    color: 'black',
    lineHeight: h('9%'),
    textTransform: 'capitalize',
  },
  balancemainTxt: {
    fontSize: scale(16),
    color: textcolor,
    marginBottom: h('0.5%'),
  },
  batteriesdesctaxname: {
    color: 'black',
    fontSize: scale(16),
  },
  batterytypemainheading: {
    fontSize: scale(16),
    color: 'black',
    width: '90%',
    alignSelf: 'center',
    marginVertical: h('4%'),
  },
  confirmcardatatitletxtcard: {
    fontSize: scale(18),
    color: 'black',
  },
  termscreenbtntxt: {
    fontSize: scale(16),
    color: maincolor,
    fontWeight: 'bold',
  },
  confirmcardatadesctxtcard: {
    fontSize: scale(14),
    color: c0color,
    marginTop: 6,
  },
  textinputfamilyclassAll: {
    //marginBottom:5
    color: 'black',
  },
  celltxt: {
    width: w('12%'),
    height: w('12%'),
    lineHeight: w('12%'),
    fontSize: h('2.9%'),
    backgroundColor: '#FBFBFB',
    borderWidth: 1,
    borderColor: '#BFD0E5',
    textAlign: 'center',
    marginRight: w('3%'),
    borderRadius: 5,
  },
  verifcationtime: {
    color: textcolor,
    fontSize: scale(16),
    fontWeight: '400',
  },
  termscreenlistid: {
    fontWeight: '900',
    color: 'black',
    fontSize: scale(16),
  },
  complpaydatewalatxt: {
    fontSize: scale(14),
    color: textcolor,
    marginLeft: w('2%'),
  },
  completepayplacetxt: {
    fontSize: scale(14),
    color: textcolor,
    marginLeft: w('1%'),
  },
  home4btnmaintxt: {
    marginTop: h('1%'),
    fontSize: scale(14),
    color: 'black',
  },
  loginInputheading: {
    color: textcolor,
    marginBottom: scale(16),
    fontSize: h('2.3%'),
    fontWeight: '400',
  },
  signupagreetxtunder: {
    color: maincolor,
    textDecorationLine: 'underline',
    textDecorationColor: maincolor,
  },
  signupagreetxt: {
    width: '70%',
    marginLeft: 15,
    fontSize: scale(14),
    color: textcolor,
  },
  carsaddscreenvaluetxt: {
    color: 'black',
    fontSize: scale(14),
  },
  carsaddscreenmainhed: {
    fontSize: scale(14),
    color: 'black',
    textAlign: 'center',
    marginVertical: h('9%'),
  },
  loginbotonswitchnav: {
    fontSize: scale(14),
    color: textcolor,
    fontWeight: 'bold',
  },
  home4btnsubscrip: {
    color: textcolor,
    fontSize: scale(10),
    fontWeight: '600',
    position: 'absolute',
    bottom: h('1.1%'),
  },
  tipscreenmainQuestionText: {
    fontSize: scale(16),
    color: 'black',
  },
  completpaydatetimetxt: {width: '100%', fontSize: h('2.7%'), color: 'black'},
  completepaytitle: {color: 'black', fontSize: scale(16)},
  batteriesdescbatterydes: {
    color: 'black',
    fontSize: scale(16),
    width: '100%',
    alignSelf: 'center',
  },
  oilsectorfilltxtspae: {
    width: '85%',
    height: '100%',
    fontSize: scale(14),
    color: 'black',
    alignSelf: 'flex-start',
    textAlign: 'left',
  },
  oilselectrmainheadingtxt: {
    width: '70%',
    fontSize: h('2.3%'),
    color: 'black',
    fontWeight: '600',
    alignSelf: 'flex-start',
    textAlign: 'left',
  },
  orderscreenststus: {textTransform: 'capitalize'},
  batteriesdescbatterydesched: {
    color: textcolor,
    fontSize: scale(14),
    width: '60%',
    alignSelf: 'center',
    marginBottom: h('1%'),
  },
  oilfilterrefiltxt: {
    color: 'black',
    fontSize: scale(20),
    fontWeight: '400',
    width: '100%',
    alignSelf: 'center',
    marginBottom: h('1.5%'),
  },
  settingscreenfirsttxtset: {
    fontSize: scale(16),
    color: 'black',
  },
  signupmaintxt: {
    color: 'white',
    fontSize: scale(20),
    fontWeight: 'bold',
    width: '90%',
    marginTop: 50,
  },
  settingscreensectxtset: {
    fontSize: scale(14),
    color: textcolor,
    width: '15%',
  },
  myorderscreendattxt: {
    fontSize: scale(12),
    color: textcolor,
  },
  verficationidnotetxt: {
    color: textcolor,
    fontSize: scale(12),
    fontWeight: '400',
    marginBottom: h('0.7%'),
  },
  myorderscreentitle: {fontSize: scale(14), color: 'black', marginVertical: 2},
  myorderscreenorderidval: {fontWeight: 'bold', color: 'black'},
  myorderscreenorderid: {
    fontSize: scale(12),
    color: c0color,
  },
  batteriesdescbatterytitle: {
    color: 'black',
    fontSize: scale(20),
    fontWeight: '400',
    width: '100%',
    alignSelf: 'center',
    marginBottom: h('1.5%'),
  },
  balancesubtxt: {fontSize: scale(12), color: textcolor},
  balancevaluetxt: {fontSize: scale(16), color: 'black', fontWeight: 'bold'},
  oilfilterdescripttxt: {
    color: 'black',
    fontSize: scale(16),
    width: '70%',
    alignSelf: 'center',
  },
  tiredesctaxname: {
    color: 'black',
    fontSize: h('2.3%'),
    width: '50%',
    textAlign: 'left',
  },
  changebtntxt: {
    color: maincolor,
    textDecorationColor: maincolor,
    textDecorationLine: 'underline',
    fontSize: scale(16),
  },
  tamarloginrequestnum: {
    color: textcolor,
    fontSize: scale(12),
    fontWeight: '400',
    width: '90%',
    alignSelf: 'center',
    marginTop: h('1.5%'),
  },
  curvedHeaderscreenname: {
    fontSize: scale(18),
    fontWeight: '400',
    textTransform: 'capitalize',
    color: textcolor,
  },
});
export default TextStyles;
